sudo: required

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - realpath
    - wget

language: cpp

jdk:
  - oraclejdk8

env:
  - BAZEL_VERSION=0.5.2

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase
    - $HOME/clang

before_install:
  - mkdir -p ${HOME}/bazel/install
  - cd ${HOME}/bazel/install
  - wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  - chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
  - sudo ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
  - cd ${TRAVIS_BUILD_DIR}

script:
  - script/check-style
  - CC=/usr/bin/gcc-4.9 CXX=/usr/bin/g++-4.9 bazel --output_base=${HOME}/bazel/outbase test //...
